name: Auto-generate Documentation
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - name: Generate Documentation with ReDoT
        uses: fac-31/ReDoT@v1  # Replace with actual published action path
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull: ${{ github.event.pull_request.number }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # github_token is optional - defaults to ${{ github.token }}
